[GLOBAL]
pants_version = "2.21.0"
colors = true
backend_packages = [
  "pants.backend.docker",
  "pants.backend.build_files.fmt.ruff",
  "pants.backend.project_info"
]

[python]
interpreter_constraints = ['==3.12.*']

[source]
root_patterns = [
  "/"
]

[docker]
build_args = [
  "USER_NAME=numa",
  "GIT_CURRENT_BRANCH",
  "GIT_COMMIT",
  "GIT_REPOSITORY_ROOT"
]
